config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { 
    registrations: "users/registrations", 
    confirmations: "users/confirmations",
    sessions: "users/sessions"
  }

  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end  

  root 'welcome#index'

  get 'welcome', to: 'welcome#index', as: :welcome_index

  resources :likes, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
  get '/unfolloweds', to: 'follows#unfolloweds', as: 'unfolloweds'
  resources :shared_post, only: [:create, :destroy]
  resources :posts

  resources :search, only: [:index]

  resources :notifications, only: [:index, :create, :destroy, :update]

  get '/settings', to: 'users/settings#index', as: 'settings'

  devise_scope :user do 
    get '/users/sign_up/avatar', to: 'users/registrations#avatar', as: 'signup_avatar'
    put '/users/sign_up/avatar', to: 'users/registrations#signup_set_avatar', as: 'signup_set_avatar'
    get '/:username(/:tab)', to: 'users/registrations#show',  constraints: { tab: /posts|likes|comments/ }, as: 'user'
    get '/:username/followers', to: 'users/registrations#show_followers', as: 'user_followers'
    get '/:username/followings', to: 'users/registrations#show_followings', as: 'user_followings'
  end

  # Uncomment the condition in development to see normal errors
  # if !Rails.env.development?
    get '*unmatched', to: 'application#route_not_found', constraints: lambda { |req|
      req.path.exclude? 'rails/active_storage'
    }
  # end

end

app/models/post.rb
# frozen_string_literal: true

# Post model
class Post < ApplicationRecord
  validates :content, presence: true

  belongs_to :user, optional: true
  belongs_to :deleted_user, optional: true

  has_many_attached :images
  has_many :shared_posts_relation, class_name: 'SharedPost', foreign_key: :post_id, dependent: :destroy
  has_many :sharers, through: :shared_posts_relation, source: :user
  
 
  has_many :likes, dependent: :destroy

  def liked_by?(user)
    likes.exists?(user: user)
  end

  def unliked_by(user)
    likes.find_by(user_id: user.id).destroy
  end

  def shared_by?(user)
    shared_posts_relation.exists?(user: user)
  end

  # Associate a post as to a parent post
  # this allows to treat it as a comment when needed
  belongs_to :parent, class_name: 'Post', optional: true

  # Get the posts that belongs to another post
  scope :comments, ->(post) { where(parent_id: post.id) }

  # Recursivelly calls all the parents/ancestors
  scope :ancestors, ->(post, ancestors_list) {
    if post.parent.nil?
      return ancestors_list
    else
      ancestors_list.unshift(post.parent)
    end
    ancestors(post.parent, ancestors_list)
  }

  def swap_to_deleted_user(deleted_id)
    self.user_id = nil
    self.deleted_user_id = deleted_id
    save
  end

  has_many :notifications, as: :notifiable, dependent: :destroy
  
  after_save :create_notification

  private
  
  def create_notification
    if self.parent.present? && self.user_id != self.parent.user_id
      Notification.create(
        sender_id: self.user_id,
        receiver_id: self.parent.user_id,
        notifiable_id: self.id,
        notifiable_type: "Post"
      )
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :authenticate_user!
  before_action :redirect_if_not_signed_in!

  def index

    users_ids = @user_suggestions.follows_ids
    @publications = Publications.new(users_ids, params[:page], 10)

    @post = Post.new # fills the the "new post" form

    if params[:page].present?
      if @publications.posts.count.zero?
        render turbo_stream:
          turbo_stream.append('posts_list', partial: 'posts/no-posts')
      end
      
      render turbo_stream:
        turbo_stream.append(:posts_list,
          partial: 'posts/posts-list', locals: { posts: @publications.posts } )
    end
           
  end

  def show
    @post = Post.find_by(id: params[:id])
    if @post.present?
      @comment = Post.new(parent: @post)
      @comments = Post.comments(@post)
      @ancestors = Post.ancestors(@post, [])
    end
  end

  def new
    @post = Post.new
    if params[:parent_id].present?
      @parent = Post.find(params[:parent_id])
      @post.parent_id = @parent.id
      render "comments/new_modal"
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save

      if @post.parent.present?  

        flash[:posted] = "Your comment was posted!"

        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update(
                "comment_#{@post.parent.id}",
                partial: "comments/comment-button",
                locals: { post: @post.parent }
              ),
              turbo_stream.update(
                "flash_message",
                partial: "shared/flash_message",
                locals: { post: @post }
              )
            ]
          end
        end

      else
      
        flash[:posted] = "Posted successfully!"
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update(
                "flash_message",
                partial: "shared/flash_message",
                locals: { post: @post }
              ),
              turbo_stream.update(
                "form_new_post",
                partial: "posts/new/form",
                locals: { post: Post.new }
              )
            ]
          end
        end

      end

    else
      @errors = @post.errors.full_messages
      render 'posts/index', status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.shared_posts_relation.destroy_all
    @post.update(deleted: true)
    flash[:notice] = "Your post was deleted"
    render turbo_stream:
      turbo_stream.replace("frame_post_#{@post.id}", partial: "posts/deleted", locals: { post: @post })
  end
  
  private 

  def post_params
    params.require(:post).permit(:content, :user_id, :parent_id, images: [])
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/components/_actions.html.erb
<div class="post-actions">

  <%= render partial: 'likes/like',
    locals: {
      post: post,
      action_prefix: action_prefix } %>

  <%= render partial: 'shared_posts/shared_post_button',
    locals: {
      post: post,
      action_prefix: action_prefix }%>

  <%= render partial: 'comments/comment-button', locals: { post: post } %>
</div>

app/views/posts/components/_avatar.html.erb
<%= link_to user_path(username: user.username), data: { turbo: false } do %>
  <div class="post-avatar-container">
    <% if user.avatar.present? && user.avatar.attached? %>
      <%= image_tag user.avatar, class: "post-user-avatar" %>
    <% else %>
      <%= image_tag "", class: "post-user-avatar empty-avatar" %>
    <% end %>
  </div>
<% end %>

app/views/posts/components/_comment-button.html.erb
<%= link_to new_post_path(parent_id: post.id), data: { turbo_frame: "comment" }, class: "action-button comment-button" do %>
    <%= icon("fa-regular", "comment")%>
    
    <%= Post.comments(post).where(deleted: false).count %>
<% end %>

app/views/posts/components/_content.html.erb
<div class="post-content">
    <p><%= post.content %></p>

    <% if post.images.attached? %>
	<div class="post-images-container">
	    <% post.images.each do |image| %>

		<%= image_tag image, class: "post-image" %>
	    <% end %>
	</div>
    <% end %>
</div>

app/views/posts/components/_metadata.html.erb
<div class="<%= is_current_post ? "post-meta" : "post-simple-meta" %>">

  <%= link_to user_path(username: post.user.username), 
    data: { turbo: false },
    class: "post-user-name" do %>
    <%= post.user.name %>
    <%= render partial: "components/verified", locals: { verified: post.user.verified } %>
    <p class="post-user-username">@<%= post.user.username %></p>
  <% end %>

  <% if !is_current_post %>
  <p class="post-time">
    <% if view == :index %>
      <%= format_time_ago(post.created_at) %>
    <% else %>
      <%= post.created_at.strftime("%-I:%M %p · %-d %b. %Y") %>
    <% end %>
  </p>
  <% end %>

  <% if !is_parent_of_comment %>
    <div class='post-options' data-controller="menu-options">
      <button class="option-button" data-action="click->menu-options#show">
        <%= icon("fa-solid", "ellipsis-vertical") %>
      </button>
      <%= render partial: 'posts/options', locals: {post: post} %>
    </div>
  <% end %>

</div>

app/views/posts/components/_post.html.erb
<div class="post">
  <div class="post-header">
    <div class="post-avatar">
      <% if post.user.avatar.attached? %>
        <%= image_tag post.user.avatar, class: "post-avatar" %>
      <% end %>
    </div>
    <div class="post-meta">
      <strong><%= post.user.name %></strong> 
      @<%= post.user.username %>
    </div>
    <div class='post-delete'>
      <p>Delete</p>
    </div>
  </div>
  <div class="post-content">
    <p><%= post.content %></p>
    <% if post.images.attached? %>
      <%= image_tag post.images.first, class: "post-image" %>
    <% end %>
  </div>


  <div class="post-actions post-meta">
    <% if view == :index %>
      <%= format_time_ago(post.created_at) %>
    <% else %>
      <%= post.created_at.strftime("%-I:%M %p · %-d %b. %Y") %>
    <% end %>
  </div>

  <hr />

  <div class="post-actions">
    <a href="#">Like</a>
    <a href="#">Repost</a>
    <%= link_to "Comments", post_path(post) %>
  </div>
</div>

app/views/posts/components/_replying-sign.html.erb
<% if parent.present? && view == :index  %>
  <div class="post-replying-sign">Replying to
		<% parent_user = parent.user.present? ? parent.user : parent.deleted_user %>

		<%= link_to user_path(username: parent_user.username), 
			data: { turbo: false },
			class: "post-user-link" do %>
				@<%= parent_user.username %>
		<% end %>
	
  </div>
<% end %>