config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { 
    registrations: "users/registrations", 
    confirmations: "users/confirmations",
    sessions: "users/sessions"
  }

  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end  

  root 'welcome#index'

  get 'welcome', to: 'welcome#index', as: :welcome_index

  resources :likes, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
  get '/unfolloweds', to: 'follows#unfolloweds', as: 'unfolloweds'
  resources :shared_post, only: [:create, :destroy]
  resources :posts

  resources :search, only: [:index]

  resources :notifications, only: [:index, :create, :destroy, :update]

  get '/settings', to: 'users/settings#index', as: 'settings'

  devise_scope :user do 
    get '/users/sign_up/avatar', to: 'users/registrations#avatar', as: 'signup_avatar'
    put '/users/sign_up/avatar', to: 'users/registrations#signup_set_avatar', as: 'signup_set_avatar'
    get '/:username(/:tab)', to: 'users/registrations#show',  constraints: { tab: /posts|likes|comments/ }, as: 'user'
    get '/:username/followers', to: 'users/registrations#show_followers', as: 'user_followers'
    get '/:username/followings', to: 'users/registrations#show_followings', as: 'user_followings'
  end

  # Uncomment the condition in development to see normal errors
  # if !Rails.env.development?
    get '*unmatched', to: 'application#route_not_found', constraints: lambda { |req|
      req.path.exclude? 'rails/active_storage'
    }
  # end

end

app/models/shared_post.rb
class SharedPost < ApplicationRecord
  belongs_to :user
  belongs_to :post

  has_many :notifications, as: :notifiable, dependent: :destroy
  
  after_save :create_notification

  private
  
  def create_notification
    if self.user_id != self.post.user_id
      Notification.create(
        sender_id: self.user_id,
        receiver_id: self.post.user_id,
        notifiable_id: self.id,
        notifiable_type: "SharedPost"
      )
    end
  end

end

app/controllers/shared_post_controller.rb
# frozen_string_literal: true

# SharedPost controller
class SharedPostController < ApplicationController
  def index
    @sharedPosts = SharedPost.all.order(created_at: :desc).load_async
    debug
  end

  def create
    @post = Post.find(params[:id])

    return if @post.shared_by?(current_user)

    new_repost = @post.shared_posts_relation.create(user: current_user) 

    updatable_frames = get_updatable_reposts_frames()
    updatable_frames.append(
      turbo_stream.prepend("posts_list",
        partial: 'shared_posts/shared_post',
        locals: { repost: new_repost })
    )

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: updatable_frames
      end
    end

  end

  def destroy
    @post = Post.find(params[:id])

    return unless @post.shared_by?(current_user)

    # Getting post
    shared_post = @post.shared_posts_relation.find_by(user: current_user)
    
    if shared_post
      shared_post.destroy
    end

    updatable_frames = get_updatable_reposts_frames()
    updatable_frames.append(
      turbo_stream.remove(
        "shared_post_#{shared_post.id}_by_user_#{shared_post.user.id}"
      )
    )

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: updatable_frames
      end
    end
      
  end

  private

  def get_updatable_reposts_frames
    visible_reposts = @post.shared_posts_relation.where(user_id: @user_suggestions.follows_ids(true))
    updatable_frames = visible_reposts.map { |repost|
      action_prefix = "shared_post_#{repost.id}_by_user_#{repost.user.id}"
      turbo_stream.replace("#{action_prefix}_share_button",
            partial: 'shared_posts/shared_post_button',
            locals: { post: @post, action_prefix: action_prefix })
    }

    updatable_frames.append(
      turbo_stream.replace("post_#{@post.id}_share_button",
        partial: 'shared_posts/shared_post_button',
        locals: { post: @post, action_prefix: "post_#{@post.id}" }
      )
    )

    updatable_frames
  end

end

app/views/shared_posts/_removed.html.erb
<div class="repost-header">
    <%= icon('fa-solid', 'retweet') %>
    <%= repost.user.name %> reposted
</div>

<div class="post border-post parent-post-container bg-post">
    Removed
</div>

app/views/shared_posts/_shared_post.html.erb
<%= turbo_frame_tag "shared_post_#{repost.id}_by_user_#{repost.user.id}" do %>

  <div class="repost-header">
    <%= icon('fa-solid', 'retweet') %>
    <%= repost.user.name %> reposted
  </div>

  <div class="post border-post parent-post-container bg-post">

    <%= link_to repost.post, data: { turbo: false }, class: "post-link" do %><% end %>

    <% if repost.post.user %>
      
      <%= render partial: "posts/simple-post-left",
        locals: { 
          post: repost.post, 
          is_parent_of_comment: false } %>

      <div class="parent-post-right">     

        <!-- Name, Username, Date -->
        <%= render partial: "posts/components/metadata",
          locals: { 
            post: repost.post, 
            is_current_post: false, 
            is_parent_of_comment: false, 
            view: :index } %>

        <%= render partial: "posts/components/replying-sign",
          locals: {
            parent: repost.post.parent, 
            view: :index } %>

        <%= render partial: "posts/components/content" , locals: { post: repost.post }%>
        <%= render partial: "posts/components/actions",
          locals: {
            post: repost.post,
            action_prefix: "shared_post_#{repost.id}_by_user_#{repost.user.id}" }%>
      </div>

    <% elsif repost.post.deleted_user %>
      This post is not available anymore
    <% end %>

  </div>

<% end %>

app/views/shared_posts/_shared_post_button.erb
<%= turbo_frame_tag "shared_#{post.id}" do %>

  <% if post.shared_by?(current_user) %>

    <%= link_to shared_post_path(id: post.id), remote: true,
      data: { turbo_method: :delete },
      class: 'action-button shared-button' do %>

      <%= icon('fa-solid', 'retweet') %>
      <%= post.shared_posts_relation.count %>
    <% end %>

  <% else %>
  
    <%= link_to shared_post_index_path(id: post.id), remote: true,
      data: { turbo_method: :post },
      class: 'action-button' do %>

      <%= icon('fa-solid', 'retweet') %>
      <%= post.shared_posts_relation.count %>
    <% end %>
      
  <% end %>

<% end %>

app/views/shared_posts/_shared_post_button.html.erb
<%= turbo_frame_tag "#{action_prefix}_share_button" do %>

  <% if post.shared_by?(current_user) %>

    <%= link_to shared_post_path(id: post.id),
      remote: true,
      data: { turbo_method: :delete },
      class: 'action-button shared-button' do %>

      <%= icon('fa-solid', 'retweet') %>
      <%= post.shared_posts_relation.count %>
    <% end %>

  <% else %>
  
    <%= link_to shared_post_index_path(id: post.id),
      remote: true,
      data: { turbo_method: :post },
      class: 'action-button' do %>

      <%= icon('fa-solid', 'retweet') %>
      <%= post.shared_posts_relation.count %>
    <% end %>
      
  <% end %>

<% end %>