config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { 
    registrations: "users/registrations", 
    confirmations: "users/confirmations",
    sessions: "users/sessions"
  }

  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end  

  root 'welcome#index'

  get 'welcome', to: 'welcome#index', as: :welcome_index

  resources :likes, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
  get '/unfolloweds', to: 'follows#unfolloweds', as: 'unfolloweds'
  resources :shared_post, only: [:create, :destroy]
  resources :posts

  resources :search, only: [:index]

  resources :notifications, only: [:index, :create, :destroy, :update]

  get '/settings', to: 'users/settings#index', as: 'settings'

  devise_scope :user do 
    get '/users/sign_up/avatar', to: 'users/registrations#avatar', as: 'signup_avatar'
    put '/users/sign_up/avatar', to: 'users/registrations#signup_set_avatar', as: 'signup_set_avatar'
    get '/:username(/:tab)', to: 'users/registrations#show',  constraints: { tab: /posts|likes|comments/ }, as: 'user'
    get '/:username/followers', to: 'users/registrations#show_followers', as: 'user_followers'
    get '/:username/followings', to: 'users/registrations#show_followings', as: 'user_followings'
  end

  # Uncomment the condition in development to see normal errors
  # if !Rails.env.development?
    get '*unmatched', to: 'application#route_not_found', constraints: lambda { |req|
      req.path.exclude? 'rails/active_storage'
    }
  # end

end

app/models/follow.rb
# frozen_string_literal: true

# Follow model
class Follow < ApplicationRecord
  # The user that follows
  belongs_to :follower, foreign_key: :follower_id, class_name: 'User'

  # The user that is followed by another
  belongs_to :following, foreign_key: :following_id, class_name: 'User'

  validates :follower_id, uniqueness: { scope: :following_id }

  has_many :notifications, as: :notifiable, dependent: :destroy

  after_save :create_notification

  private
  
  def create_notification
    Notification.create(
      sender_id: self.follower_id,
      receiver_id: self.following_id,
      notifiable_id: self.id,
      notifiable_type: "Follow"
    )
  end

end

app/controllers/follows_controller.rb
# frozen_string_literal: true

# Follows controller
class FollowsController < ApplicationController

  def unfolloweds
    @user_suggestions.page_number = params[:page].present? ? params[:page].to_i : 1

    render turbo_stream: 
      turbo_stream.append(:modal_users_suggestions_list,
        partial: 'follows/modal-users-suggestions-list',
        locals: { firsts_to_follow: @user_suggestions.firsts_to_follow }
      )
  end

  def create
    # getting the following user
    following_id = params[:id]
    following_user = User.find_by(id: following_id)
    size = params[:size]

    # create a follow relationship
    current_user.create_follow(following_user);

    # render and replace all follow buttons and counters
    render turbo_stream: [
      # follow button on user view
      turbo_stream.replace(
        "follow_button_#{following_id}_user_suggest", 
        partial: 'components/follow-button', 
        locals: { 
          user: following_user,
          size: "sm",
          componet_id: "user_suggest"
        }
      ),
      turbo_stream.replace(
        "follow_button_#{following_id}_user_info", 
        partial: 'components/follow-button', 
        locals: { 
          user: following_user,
          size: "md",
          componet_id: "user_info"
        }
      ),
      turbo_stream.replace(
        "follow_button_#{following_id}_modal", 
        partial: 'components/follow-button', 
        locals: { 
          user: following_user,
          size: "md",
          componet_id: "user_info"
        }
      ),
      # follow counters on user view
      turbo_stream.replace(
        "follow_counters_#{current_user.id}", 
        partial: 'devise/registrations/components/follow-counters', 
        locals: { user: current_user }
      ),
      turbo_stream.replace(
        "follow_counters_#{following_id}", 
        partial: 'devise/registrations/components/follow-counters', 
        locals: { user: following_user }
      ),
      # follow option on post component
      turbo_stream.replace(
        "follow_post_option_#{following_id}", 
        partial: 'follows/follow', 
        locals: { following_user: following_user }
      ),
    ]
  end

  def destroy
    # getting the following user
    following_id = params[:id]
    following_user = User.find_by(id: following_id)
    size = params[:size]

    # destroy a follow relationship
    current_user.destroy_follow(following_user);
    
    # render and replace all follow buttons and counters
    render turbo_stream: [
      # follow button on user view
      turbo_stream.replace(
        "follow_button_#{following_id}_user_suggest", 
        partial: 'components/follow-button', 
        locals: { 
          user: following_user,
          size: "sm",
          componet_id: "user_suggest"
        }
      ),
      turbo_stream.replace(
        "follow_button_#{following_id}_user_info", 
        partial: 'components/follow-button', 
        locals: { 
          user: following_user,
          size: "md",
          componet_id: "user_info"
        }
      ),
      turbo_stream.replace(
        "follow_button_#{following_id}_modal", 
        partial: 'components/follow-button', 
        locals: { 
          user: following_user,
          size: "md",
          componet_id: "user_info"
        }
      ),
      # follow counters on user view
      turbo_stream.replace(
        "follow_counters_#{current_user.id}", 
        partial: 'devise/registrations/components/follow-counters', 
        locals: { user: current_user }
      ),
      turbo_stream.replace(
        "follow_counters_#{following_id}", 
        partial: 'devise/registrations/components/follow-counters', 
        locals: { user: following_user }
      ),
      # follow option on post component
      turbo_stream.replace(
        "follow_post_option_#{following_id}", 
        partial: 'follows/follow', 
        locals: { following_user: following_user }
      ),
    ]

  end
  
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_follow.html.erb
<%= turbo_frame_tag "follow_post_option_#{following_user.id}" do %>

  <% if current_user.follows?(following_user) %>

    <% url = follow_path(id: following_user.id) %>
    <%= link_to(url, remote: true, data: { turbo_method: :delete }) do %>
      <%= icon("fa-solid", "user", class: "follow-icon")%>
      Unfollow @<%= following_user.username %>
    <% end %>

  <% else %>

    <% url = follows_path(id: following_user.id) %>
    <%= link_to(url, remote: true, data: { turbo_method: :post }) do %>
      <%= icon("fa-solid", "user", class: "follow-icon")%>
      Follow @<%= following_user.username %>
    <% end %>

  <% end %>

<% end %>

app/views/follows/_modal-users-suggestions-list.html.erb
<% firsts_to_follow.each do |user| %>
  <%= render partial: 'follows/user-suggestion', locals: { user: user, size: "md",componet_id: "modal"} %>
<% end %>

<% if @user_suggestions.page_number < firsts_to_follow.total_pages %>
  <div 
    class="button button-primary w100"
    data-controller="posts-loading"
    data-action="click->posts-loading#destroyButton">

    <%= link_to "Load more", unfolloweds_path(page: @user_suggestions.next_page) %>
  </div>
<% end %>

app/views/follows/_modal-users-suggestions.html.erb
<div 
  class="modal-new-post modal-followings-suggestions" 
  data-controller="modal" 
  data-modal-target="modal">

  <div class="modal-content">
    
    <div class="modal-header">
      <h2 class="title">Discover to follow</h2>
      <div class="modal-button-container">
        <button class="submit-button" data-action="click->modal#closeModal">Skip</button>
      </div>
    </div>

    <div class="modal-follows-suggestions-list modal-scroll">

      <%= turbo_frame_tag 'modal_users_suggestions_list' do %>
        <%= render partial: 'follows/modal-users-suggestions-list',
          locals: { firsts_to_follow: @user_suggestions.firsts_to_follow } %>
      <% end %>

    </div>

  </div>
</div>

app/views/follows/_user-suggestion.html.erb
<%= link_to user_path(username: user.username), data: { turbo: false } do %>
  <div class="follow-user-suggestion">
    <% if user.avatar.present? %>
      <%= image_tag user.avatar, class: "post-user-avatar" %>
    <% else %>
      <%= image_tag "", class: "post-user-avatar" %>
    <% end %>

    <div class="user-data">
      <p class="user-name">
        <%= user.name %>
        <%= render partial: "components/verified", locals: { verified: user.verified } %>
      </p>
      <p class="user-username">@<%= user.username %></p>
    </div>
  </div>
<% end %>

<div style="position: relative;">
  <% if user != current_user %>
    <%= render partial: 'components/follow-button', locals: {user: user, size: local_assigns[:size].present? ? size : "sm", componet_id: local_assigns[:componet_id].present? ? componet_id : "user_suggest"} %>
  <% end%>
</div>

app/views/follows/_users-suggestions-list.html.erb
<div class="follow-suggestions">

  <% if @user_suggestions.to_follow.count.zero? %>
    <h2 class="title">You did it!</h2>
    <p class="title opaque-text">There's no one else to follow!</p>

  <% else %>

    <h2 class="title">Who to follow</h2>

    <% @user_suggestions.to_follow.each do |user| %>
      <%= render partial: 'follows/user-suggestion', locals: { user: user } %>
    <% end %>

  <% end %>

</div>