config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { 
    registrations: "users/registrations", 
    confirmations: "users/confirmations",
    sessions: "users/sessions"
  }

  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end  

  root 'welcome#index'

  get 'welcome', to: 'welcome#index', as: :welcome_index

  resources :likes, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
  get '/unfolloweds', to: 'follows#unfolloweds', as: 'unfolloweds'
  resources :shared_post, only: [:create, :destroy]
  resources :posts

  resources :search, only: [:index]

  resources :notifications, only: [:index, :create, :destroy, :update]

  get '/settings', to: 'users/settings#index', as: 'settings'

  devise_scope :user do 
    get '/users/sign_up/avatar', to: 'users/registrations#avatar', as: 'signup_avatar'
    put '/users/sign_up/avatar', to: 'users/registrations#signup_set_avatar', as: 'signup_set_avatar'
    get '/:username(/:tab)', to: 'users/registrations#show',  constraints: { tab: /posts|likes|comments/ }, as: 'user'
    get '/:username/followers', to: 'users/registrations#show_followers', as: 'user_followers'
    get '/:username/followings', to: 'users/registrations#show_followings', as: 'user_followings'
  end

  # Uncomment the condition in development to see normal errors
  # if !Rails.env.development?
    get '*unmatched', to: 'application#route_not_found', constraints: lambda { |req|
      req.path.exclude? 'rails/active_storage'
    }
  # end

end

app/models/post.rb
# frozen_string_literal: true

# Post model
class Post < ApplicationRecord
  validates :content, presence: true

  belongs_to :user, optional: true
  belongs_to :deleted_user, optional: true

  has_many_attached :images
  has_many :shared_posts_relation, class_name: 'SharedPost', foreign_key: :post_id, dependent: :destroy
  has_many :sharers, through: :shared_posts_relation, source: :user
  
 
  has_many :likes, dependent: :destroy

  def liked_by?(user)
    likes.exists?(user: user)
  end

  def unliked_by(user)
    likes.find_by(user_id: user.id).destroy
  end

  def shared_by?(user)
    shared_posts_relation.exists?(user: user)
  end

  # Associate a post as to a parent post
  # this allows to treat it as a comment when needed
  belongs_to :parent, class_name: 'Post', optional: true

  # Get the posts that belongs to another post
  scope :comments, ->(post) { where(parent_id: post.id) }

  # Recursivelly calls all the parents/ancestors
  scope :ancestors, ->(post, ancestors_list) {
    if post.parent.nil?
      return ancestors_list
    else
      ancestors_list.unshift(post.parent)
    end
    ancestors(post.parent, ancestors_list)
  }

  def swap_to_deleted_user(deleted_id)
    self.user_id = nil
    self.deleted_user_id = deleted_id
    save
  end

  has_many :notifications, as: :notifiable, dependent: :destroy
  
  after_save :create_notification

  private
  
  def create_notification
    if self.parent.present? && self.user_id != self.parent.user_id
      Notification.create(
        sender_id: self.user_id,
        receiver_id: self.parent.user_id,
        notifiable_id: self.id,
        notifiable_type: "Post"
      )
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :authenticate_user!
  before_action :redirect_if_not_signed_in!

  def index

    users_ids = @user_suggestions.follows_ids
    @publications = Publications.new(users_ids, params[:page], 10)

    @post = Post.new # fills the the "new post" form

    if params[:page].present?
      if @publications.posts.count.zero?
        render turbo_stream:
          turbo_stream.append('posts_list', partial: 'posts/no-posts')
      end
      
      render turbo_stream:
        turbo_stream.append(:posts_list,
          partial: 'posts/posts-list', locals: { posts: @publications.posts } )
    end
           
  end

  def show
    @post = Post.find_by(id: params[:id])
    if @post.present?
      @comment = Post.new(parent: @post)
      @comments = Post.comments(@post)
      @ancestors = Post.ancestors(@post, [])
    end
  end

  def new
    @post = Post.new
    if params[:parent_id].present?
      @parent = Post.find(params[:parent_id])
      @post.parent_id = @parent.id
      render "comments/new_modal"
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save

      if @post.parent.present?  

        flash[:posted] = "Your comment was posted!"

        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update(
                "comment_#{@post.parent.id}",
                partial: "comments/comment-button",
                locals: { post: @post.parent }
              ),
              turbo_stream.update(
                "flash_message",
                partial: "shared/flash_message",
                locals: { post: @post }
              )
            ]
          end
        end

      else
      
        flash[:posted] = "Posted successfully!"
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update(
                "flash_message",
                partial: "shared/flash_message",
                locals: { post: @post }
              ),
              turbo_stream.update(
                "form_new_post",
                partial: "posts/new/form",
                locals: { post: Post.new }
              )
            ]
          end
        end

      end

    else
      @errors = @post.errors.full_messages
      render 'posts/index', status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.shared_posts_relation.destroy_all
    @post.update(deleted: true)
    flash[:notice] = "Your post was deleted"
    render turbo_stream:
      turbo_stream.replace("frame_post_#{@post.id}", partial: "posts/deleted", locals: { post: @post })
  end
  
  private 

  def post_params
    params.require(:post).permit(:content, :user_id, :parent_id, images: [])
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_deleted.html.erb
<div class="post border-post <%= "current-post" if defined?(is_current_post) && is_current_post  %>">    
    This post was deleted by it's author
</div>

app/views/posts/_no-posts.html.erb
<div class="post border-post">
    <p>There's no posts</p>
</div>

app/views/posts/_options.html.erb
<div class="menu-options hidden" data-menu-options-target="options">
  <% if current_user.id == post.user_id %>
    <div class="menu-option">
      <%= icon("fa-solid", "trash-can", class: "delete-icon")%>
      <%= link_to "Delete post", post_path(post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </div>
  <% end %>
  
  <% if current_user.id != post.user_id %>
    <div class="menu-option">
      <%= render partial: "follows/follow", locals: { following_user: post.user } %>
    </div>
  <% end %>
</div>

app/views/posts/_parent.html.erb
<%= turbo_frame_tag "frame_#{dom_id(post)}" do %>

<div class="post 
            parent-post-container
            <%= "border-post bg-post" if !is_parent_of_comment %>">

  <%= link_to post, data: { turbo: false }, class: "post-link" do %><% end %>

  <% if post.user %>
    
    <%= render partial: "posts/simple-post-left",
      locals: {
        post: post,
        is_parent: true,
        is_parent_of_comment: is_parent_of_comment } %>

			<div class="parent-post-right">

        <!-- Name, Username, Date -->
        <%= render partial: "posts/components/metadata",
          locals: { 
            post: post, 
            is_current_post: false, 
            is_parent_of_comment: is_parent_of_comment,
            view: :show } %>

        <%= render partial: "posts/components/content", locals: { post: post }%>

        <%= render partial: "posts/components/actions",
          locals: { post: post, action_prefix: dom_id(post) }%>

      </div>
			  
		<% elsif post.deleted_user %>
			This post is not available anymore
		<% end %>

	</div>

<% end %>

app/views/posts/_post-simple.html.erb
<%= turbo_frame_tag "frame_#{dom_id(post)}" do %>

  <div class="post border-post parent-post-container bg-post">

    <%= link_to post, data: { turbo: false }, class: "post-link" do %><% end %>

    <% if post.user %>
      
      <%= render partial: "posts/simple-post-left",
      locals: { post: post, is_parent_of_comment: is_parent_of_comment } %>

      <div class="parent-post-right">     

        <!-- Name, Username, Date -->
        <%= render partial: "posts/components/metadata",
          locals: { post: post, is_current_post: false, is_parent_of_comment: is_parent_of_comment, view: view } %>

        <%= render partial: "posts/components/replying-sign", locals: { parent: post.parent, view: view } %>
  	    <%= render partial: "posts/components/content" , locals: { post: post }%>
  	    <%= render partial: "posts/components/actions",
          locals: { post: post, action_prefix: dom_id(post) }%>
  		</div>

		<% elsif post.deleted_user %>
		  This post is not available anymore
		<% end %>

	</div>

<% end %>

app/views/posts/_post.html.erb
<%= turbo_frame_tag post do %>
    
  <div class="post border-post current-post">

    <% if post.user %>
    
    <% if post.parent.present? && !post.parent.deleted %>
      <span class="top-thread-line-container">
        <span class="top-thread-line"></span>
      </span>
    <% end %>

    <div class="post-header">

      <%= render partial: "posts/components/avatar", locals: { user: post.user }%>

      <!-- Name, Username, Date -->
      <%= render partial: "posts/components/metadata",
        locals: { 
          post: post, 
          is_current_post: is_current_post, 
          is_parent_of_comment: false, 
          view: view } %>
    </div>

      <%= render partial: "posts/components/content" , locals: { post: post }%>

    	<div class="post-time-bottom post-meta">
    	  <% if view==:index %>
    	    <%= format_time_ago(post.created_at) %>
    	  <% else %>
    	    <%= post.created_at.strftime("%-I:%M %p · %-d %b. %Y") %>
    	  <% end %>
    	</div>

    	<hr />
    	<%= render partial: "posts/components/actions",
        locals: { post: post, action_prefix: dom_id(post)}%>

    <% elsif post.deleted_user %>
      This post is not available anymore
    <% end %>

  </div>

<% end %>

app/views/posts/_posts-list.html.erb
<% posts.each do |element| %>

    <%if element.class == Post %>
	<%= render partial: 'posts/post-simple',
		   locals: {
		       view: :index,
		       post: element,
		       is_parent_of_comment: false } %>

    <%else%>
	<%= render partial: 'shared_posts/shared_post', locals: {view: :index, repost: element} %>
    <%end%>

<%end%>

<% if @publications.page_number < posts.total_pages %>
	<div
		class="button button-primary w100"
		data-controller="posts-loading"
		data-action="click->posts-loading#destroyButton">
		<%= link_to "Load more", posts_path(page: @publications.next_page), remote: true %>
	</div>
<% end %>

app/views/posts/_posts_list.erb
<% if posts.any? %>

  <div class='post-container'>
    <%= turbo_frame_tag 'posts_list' do %>
      <%= render partial: 'posts/posts-list', locals: { posts: posts } %>
    <% end %>      
  </div>

<% else %>
  <%= render 'posts/no-posts' %>
<% end %>

app/views/posts/_search.html.erb
<%= turbo_frame_tag "search_results" do %>
  <% if validate %>
    <ul>
      <% users.each do |user| %>
        <li>
          <%= user.name %> - <%= user.email %> <!-- O muestra cualquier otro atributo que quieras -->
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>No se encontraron usuarios.</p>
  <% end %>
<% end %>

app/views/posts/_simple-post-left.html.erb
<% if defined?(is_parent) && 
      is_parent && 
      post.parent.present? && 
      !post.parent.deleted && 
      !is_parent_of_comment %>
  <span class="top-thread-line-container">
    <span class="top-thread-line"></span>
  </span>
<% end %>

<div class="parent-post-left">

  <%= render partial: "posts/components/avatar", locals: { user: post.user } %>

  <% if defined?(is_parent) && is_parent && !is_parent_of_comment %>
    <span class="thread-line"></span>
  <% else %>
    <span class="space-thread-line"></span>
  <% end %>

</div>

app/views/posts/index.html.erb
<div class='home-container'>
  <div class="form-new-post-container">
    <%= render partial: "posts/new/form", locals: { post: @post } %>
  </div>

  <%= render partial: 'posts/posts_list', locals: { posts: @publications.posts } %>
</div>

app/views/posts/new.html.erb
<%= render partial: "posts/new/form", locals: { post: @post } %>

app/views/posts/new_comment.html.erb
<%= turbo_frame_tag "comment" do %>

  <div class="modal-new-post">
    <div class="modal-new-post-content">
      <%= link_to "X", class: "close-button" %>

      <%= render partial: "posts/parent",
        locals: {
          post: @parent,
          is_parent_of_comment: true
        } %>

      <%= render partial: "posts/new/form",
        locals: {
          post: @post,
          is_parent_of_comment: true } %>

    </div>
  </div>

<% end %>

app/views/posts/show.html.erb
<div class='post-container'>

    <% if @post.present? %>

    <% @ancestors.each do |post| %>
  	  <% if post.deleted %>
  	      <%= render partial: 'posts/deleted' %>
  	  <% else %>
  	      <% locals_parent = { view: :show, is_parent_of_comment: false, post: post } %>
  	      <%= render partial: 'posts/parent', locals: locals_parent %>
  	  <% end %>
    <% end %>

    <span data-controller="auto-scroll" data-action="load@window->auto-scroll#scrollToThis">
  	  <% if @post.deleted %>
  	      <%= render partial: 'posts/deleted', locals: { is_current_post: true } %>
  	  <% else %>
        <% post_locals = {post: @post, view: :show, is_current_post: true, is_parent_of_comment: false } %>
        <%= render partial: 'posts/post', locals: post_locals %>

        <% if !@post.user.nil? && !@post.deleted %>
          <%= render partial: 'posts/new/form',
            locals: { post: @comment, is_parent_of_comment: true, is_current_post: true }%>
        <% end %>

  	  <% end %>
    </span>


    <%= render partial: 'posts/post-simple',
    collection: @comments.where(deleted: false), as: :post,
    locals: { view: :show, is_parent_of_comment: false } %>
  
  <% else %>

    <div class="post border-post current-post">
      Post doesn't exists
    </div>

  <% end %>
    
</div>